name: Compilar APK TeleFacil

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'

      - name: Preparar dependencias y Android
        run: |
          flutter create --platforms=android .
          flutter pub add http video_player chewie shared_preferences wakelock_plus
          flutter pub get
          sed -i -E 's/id "org.jetbrains.kotlin.android" version "[^"]+"/id "org.jetbrains.kotlin.android" version "2.1.0"/' android/settings.gradle || true

      - name: Compilar APK (Release)
        run: flutter build apk --release

      - name: Subir APK descargable
        uses: actions/upload-artifact@v4
        with:
          name: TeleFacil-Instalador
          path: build/app/outputs/flutter-apk/app-release.apk
